### ISSUE TITLE
Ok...you became kind of a master.

### ISSUE THREAD

**Issue by recoil24** [dumitru1216/cs2-external-evo#3]
Hi, I always thought you were a dumb paster but seeing this work changes my whole world. You became a master of cs coding. May I ask if you plan to make or release an internal hvh cheat? :P

**Comment by maecry** [comment]
how is this master when he is still pasting around?? inconsistent code-style(pasted from several sources (looks into the framework.cpp where he did pasted word by word from cazz video some part) maybe you also a dumb paster as well no?

**Comment by recoil24** [comment]
> how is this master when he is still pasting around?? inconsistent code-style(pasted from several sources (looks into the framework.cpp where he did pasted word by word from cazz video some part) maybe you also a dumb paster as well no?

You are totally wrong. Just try to do at least half of what he does then you can criticize.

**Comment by recoil24** [comment]
> how is this master when he is still pasting around?? inconsistent code-style(pasted from several sources (looks into the framework.cpp where he did pasted word by word from cazz video some part) maybe you also a dumb paster as well no?

Oh i`m sorry for my previous post, didn`t check whom i`m replying to. You are a creator of legendary sdk for cs2...anyways yes maybe year ago he used to be what u ascribe but now his releases are not that bad + everything measures in comparison!

**Comment by maecry** [comment]
haha u're a fkin retard as well

**Comment by recoil24** [comment]
> haha u're a fkin retard as well

I'll take u down cunt, watch what Putin did say in his latest interview. You are going down very soon my little bro ;)

**Comment by dumitru1216** [comment]
Closed forever, stop arguing here
