### ISSUE TITLE
Unhandled exception in imgui_draw.cpp

### ISSUE THREAD

**Issue by T1GxR** [dumitru1216/cs2-external-evo#5]
I updated the signatures and offsets, the loader starts, but it randomly crashes if i open it directly. 
If i debug it in visual studio, i get this random error in imgui_draw.cpp file: 
![Screenshot 2024-04-18 195623](https://github.com/dumitru1216/cs2-external-evo/assets/106729571/351a0bb9-eea4-4bd9-ba0d-6be37430c039)
![Screenshot 2024-04-18 195840](https://github.com/dumitru1216/cs2-external-evo/assets/106729571/44b0a324-83e4-4ba0-9eb9-2afe199b222f)

How can i fix this? I want to fix this cheat so i can use it as an external private cheat.

**Comment by dumitru1216** [comment]
U have to install fonts

**Comment by T1GxR** [comment]
> U have to install fonts

I added the freetype.lib, freetype_debug.lib and freetype.dll files to the project which are used to get the fonts library but now i have this error: 
![Screenshot 2024-04-24 112243](https://github.com/dumitru1216/cs2-external-evo/assets/106729571/5ea65083-2088-404d-a237-5808d7e50179)
![Screenshot 2024-04-24 112456](https://github.com/dumitru1216/cs2-external-evo/assets/106729571/c52193ee-da92-4839-ac94-310faa2d5ddb)
![Screenshot 2024-04-24 113509](https://github.com/dumitru1216/cs2-external-evo/assets/106729571/85a025d5-13e8-41ca-9f7a-79748a5c9d61)

It seems to be related to SignatureArray.

**Comment by T1GxR** [comment]
> U have to install fonts

yo @dumitru1216, thx for the help. The second error is caused by the force_jump signature because its invalid. Can you give me some tips to get the new one? I can't find it anywhere...
